vich_uploader:
    db_driver: orm

    # mappings:
    #     huiles:
    #         uri_prefix: /images/huiles
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
